title: itsmaxymoo
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I create websites and software
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://itsmaxymoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
social_github: "https://github.com/itsmaxymoo"
social_pypi: "https://pypi.org/user/itsmaxymoo"
og_image: "null"

collections:
  - projects

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
timezone: America/New_York
markdown: kramdown
sass:
  style: compressed

exclude:
  - LICENSE.md
  - README.md
  - TODO.md
  - "*.sh"
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
