title: Max Loiacono | itsmaxymoo
author: Max Loiacono
description: I create websites and software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsmaxymoo.com" # the base hostname & protocol for your site, e.g. http://example.com

main_image: "assets/site-background.jpg"

# collections:
#   - projects

# Build settings
timezone: America/New_York
markdown: kramdown
sass:
  style: compressed

exclude:
  - LICENSE.md
  - README.md
  - TODO.md
  - "*.sh"
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - CNAME
