title: Max Loiacono | itsmaxymoo
author: Max Loiacono
description: I create websites and software
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itsmaxymoo.com" # the base hostname & protocol for your site, e.g. http://example.com
repo_url: "https://github.com/itsmaxymoo/itsmaxymoo.com"

date_ymd: "%Y-%m-%d"
date_natural: "%-d %B %Y"

main_image: "assets/background/flower.jpg"

collections:

  dev_projects:
    output: false
  
  worlds:
    output: true
    layout: world
    permalink: /worlds/:title
  
  content:
    output: false
    permalink: /content/:title/index.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year-:month-:day-:title/
  -
    scope:
      path: ""
      type: "drafts"
    values:
      draft: true
  -
    scope:
      path: ""
      type: "worlds"
    values:
      layout: world

# Build settings
source: "."
timezone: America/New_York
markdown: kramdown
sass:
  style: compressed

exclude:
  - LICENSE.md
  - LICENSE
  - .git*
  - README.md
  - TODO.md
  - "*.sh"
  - .vscode/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - CNAME
